### ISSUE TITLE
getmlst.py error?

### ISSUE THREAD

**Issue by tsekizuka** [katholt/srst2#101]
I tried to download MLST dataset of "Leptospira spp." and "Streptococcus thermophilus" using getmlst.py as follows:
$ getmlst.py --species "Leptospira spp." 
$ getmlst.py --species "Leptospira spp.#2"
$ getmlst.py --species "Leptospira spp.#3"
$ getmlst.py --species "Streptococcus thermophilus"
$ getmlst.py --species "Streptococcus thermophilus#2"

I could completely download "Leptospira spp.#2", "Leptospira spp.#3" and "Streptococcus thermophilus#2".
However, "Leptospira spp." and "Streptococcus thermophilus" don't work as follows:
$ getmlst.py --species "Leptospira spp."
The following 3 species match your query, please be more specific:
Leptospira spp.
Leptospira spp.#2
Leptospira spp.#3
$ getmlst.py --species "Streptococcus thermophilus"
The following 2 species match your query, please be more specific:
Streptococcus thermophilus
Streptococcus thermophilus#2

Could you teach me how to download "Leptospira spp."  and "Streptococcus thermophilus" MLST dateset ?

Regards,
tsekizuka

**Comment by katholt** [comment]
Unfortunately we can't keep track of the rules (or lack of adherence to them :)  at https://pubmlst.org/databases/ for naming different schemes for the same species

Simplest solution is to download the files yourself manually from https://pubmlst.org/databases/
