### ISSUE TITLE
Using paired end and single end reads

### ISSUE THREAD

**Issue by abouska** [katholt/srst2#102]
After trimming the fastq files I have both paired end and single end fastq files for each sample.  I don't want to exclude the single end information, Is there any way to use both the paired end and single end reads in one analysis?

**Comment by katholt** [comment]
No this is not something we've coded in. Because the bowtie2 mapping step uses soft-clipping (so we can map reads right to the ends of the genes) there is no need to work with trimmed reads, so I would suggest you just use your untrimmed paired reads.
