### ISSUE TITLE
read input problems

### ISSUE THREAD

**Issue by JeremyHorst** [katholt/srst2#103]
Hi Mike, holler at the old Samudrala group at UW.
1. The forward & reverse entry option is not working - just ends without running, says its done.
2. The requirements for filenames for --input_pe does not actually follow the format you describe, and really really should not be so stringent. Please allow any file name for read1 & read2. There are many things that folks will do to the reads before giving them to this script, which are often tracked in filenames, such as debarcoding, quality filtering, etc.

**Comment by katholt** [comment]
You can name reads however you like, but as most people are working with batches of paired read files you need to tell the program how to identify/match forward and reverse read files for the same sample.
