### ISSUE TITLE
running srst2 on python3

### ISSUE THREAD

**Issue by ssarria** [katholt/srst2#105]
Hello, 
I am new in bioinformatics & programming. I am using py3.

I want to run srst2 on some metagenomic data from  Illumina HiSeq seq.
I installed srst2 and it's ddependencies, but when I try to get " srst2 --version" on command line, I have an error msg, see below error msg

Should I not use python3.6?
Does srst2 works with python3

Thxs so much for any help!!
S

Last login: Tue Jan 23 18:11:05 on ttys000
sauls-MBP:~ saulsarria$ srst2 --version
Traceback (most recent call last):
  File "/anaconda3/bin/srst2", line 11, in <module>
    load_entry_point('srst2==0.2.0', 'console_scripts', 'srst2')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/lib/python3.6/site-packages/srst2/srst2.py", line 308
    print "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:"
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:")?
sauls-MBP:~ saulsarria$

**Comment by katholt** [comment]
srst2 was written in Python 2, see dependencies in the readme
https://github.com/katholt/srst2#current-release---v020---july-28-2016

one day we might migrate, but as Py2 is being maintained through 2020 this is not a priority (secretly hoping that we will all be working with high-accuracy long reads by then, so srst2 can retire instead of migrate to Py2!!)

**Comment by ssarria** [comment]
Thanks so much Dr. Holt.
yeah, long reads would be a great help for assambly and data analysis.
I do wet lab using HiSeq and PacBio Sequel  to  generating my own sequence
data for my graduate work.  I do not see any efforts from illumina to move
toward long reads but PacBio is getting closer, unfortunatelly PacBio error
rate is high.

I really appreciate your time and help.

I will run my project on py2.

srst2 is an awesome/great tool!!.

Have a wonderful day.

Saul
