### ISSUE TITLE
Assess multiple/all MLSTs in a single run, rather than a single species MLST?

### ISSUE THREAD

**Issue by jake9115** [katholt/srst2#107]
I'm evaluating srst2, and was able to quickly install the dependencies and package and test drive it on some paired end illumina reads for E. coli-specific MLST detection, using the `getmlst.py` command. However, I was wondering if I am missing something obvious that would allow me to assess all MLST genes in the MLST public database: `https://pubmlst.org/data/` with a single srst2 run. Of course I could do this in series, but that would require remapping all reads with bowtie2 repetitively instead of just mapping once and assessing all alleles/MLSTs mapped.

**Comment by katholt** [comment]
Hi Jake, you're not missing anything - SRST2 is designed for high-accuracy MLST allele calling direct from read sets generated from pure isolate genomes, by testing against a single input MLST database. 
If you don't know the species, I would first do a species identification step (which can be done efficiently using kmer based taxonomy assignment tools) then use that result to select the appropriate species MLST scheme.

**Comment by jake9115** [comment]
Thank you.

**Comment by andersgs** [comment]
@jake9115 you can also checkout Torsten Seemann's MLST tool: https://github.com/tseemann/mlst

**Comment by tseemann** [comment]
`mlst` only accepts contigs in .fa/.gbk (+ .gz) format however, not raw reads.
But you can do `mlst *.gbk > results.tab`.
