### ISSUE TITLE
Any convenient script for AMR-based heat map?

### ISSUE THREAD

**Issue by Anto007** [katholt/srst2#110]
Any convenient script for generating an AMR-based presence/absence heat-map for srst2 results (*ARGannot.r1__results.txt) from multiple libraries? Thanks!

**Comment by katholt** [comment]
See readme - there are some R scripts in the /scripts dir
https://github.com/katholt/srst2#plotting-output-in-r

These are old (from the original publication) and there are lots of more sophisticated options now, such as using MicroReact (microreact.org) or Phandango
