### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by capricy** [katholt/srst2#111]
Dear SRST2 Team,

I have questions about the outputs of gene typing:

1. *__genes__combined.SPI__results.txt contains "*" and "?". What are those symbols mean?

2. *__fullgenes__combined.SPI__results.txt contains annotation column and some of records is not empty. What is the information in this column? 

Examples are in the attached image file:

<img width="1239" alt="screen shot 2018-09-01 at 9 13 50 pm" src="https://user-images.githubusercontent.com/18124356/44951206-fb6f4400-ae2b-11e8-8cf5-bddd991a1733.png">

Thanks.

Kind regards,

C.

**Comment by katholt** [comment]
Hi Capricy, 

See readme - https://github.com/katholt/srst2#gene-typing
? indicates uncertainty due to low depth in some parts of the gene

The annotation is pulled from the gene database that you are using. Some DBs have annotations and some don't.
