### ISSUE TITLE
KeyError with one header in CARD

### ISSUE THREAD

**Issue by blue-moon22** [katholt/srst2#121]
I'm getting KeyError: 'gb|CP007593.1|+|2148923-2149772|ARO:3001301|RlmA(II)' with CARD database 3.0.0
A sequence follows it on the next line so I don't think it's the problem mentioned in the README

**Comment by katholt** [comment]
Looks like the database hasn't been formatted for use with SRST2?

Please see instructions in the readme:
https://github.com/katholt/srst2#generating-srst2-compatible-clustered-database-from-raw-sequences
