### ISSUE TITLE
Same output entries from db

### ISSUE THREAD

**Issue by dcastaneda5** [katholt/srst2#123]
Hi!
I am relatively new to SRST2, and I have been noticing that sometimes I get the same ID in my "full_gene" output file with different depth values, even though it has been mapped to the same ID. Sometimes I get a duplicate with the same coverage but different depth values and I was wondering why is this happening?

Thanks!

**Comment by wanyuac** [comment]
Could you give an example of your output (e.g., a section from your full\_gene report)?
