### ISSUE TITLE
Using srst2 for metagenomic screening

### ISSUE THREAD

**Issue by Anto007** [katholt/srst2#125]
Hi, I have been using your cool srst2 for detecting ARGs (not interested in alleles though!) in metagenomic library reads. What I sometimes see is that srst2 misses a few ARGs that are detectable from the final assemblies via other tools. I'm aware that srst2 was designed with cultured isolates in mind but I'm curious to know what might be at work here? Is this related to srst2 being unable to detect ARGs that are at very low depth (I always run srst2 with samtools v0.1.18) or there are other factors in play here? The best approach seems to be combining srst2 with assembly-based strategies if the intention is to capture the full diversity of ARGs that are potentially present in a given metagenomic library. I would appreciate very much your thoughts in this regard.

**Comment by katholt** [comment]
SRST2 is an allele typer, its scoring works on the assumption that there is a single allele present in the sample and aims to determine precisely what that one allele is. If there are multiple alleles present then the gene detection results are reliable, but the allele calling behaviour is unpredictable and meaningless if there is more than one allele present. 
So, if you simply want to identify the presence of 'genes' without regard to the specific alleles then you could use SRST2 and just pay attention to the gene calls and ignore the specific allele calls.
