### ISSUE TITLE
databases not updated

### ISSUE THREAD

**Issue by ptapiar** [katholt/srst2#126]
Resfinder : last update 6 years ago.

**Comment by katholt** [comment]
We do not have staff to constantly update resistance databases, and as users have different preferences as to their choice of AMR DB we leave it to users to choose and cluster their own chosen DBs. We have however now added an SRST2-formatted version of the CARD v3.0.8 database (in data/CARD_v3.0.8_SRST2.fasta) which may be useful for some users.
