### ISSUE TITLE
password request

### ISSUE THREAD

**Issue by Jeni05** [katholt/srst2#130]
Hey,

I'm very new to coding and using the command line, so I apologise if this is a very basic question.
I have some sequences that I would like to analyse using the srst2 package, and I had successfully followed the user guide until I reached the section for installing pip and git. I copied the code in the user guid for combining the instructions and I've been prompted for a password? See script below:

(base) jenniferhallam@glaroam2-152-40 ~ % sudo pip install git+https://github.com/katholt/srst2
Password:
Sorry, try again.
Password:

Any help would be greatly appreciated.
Many thanks,
Jeni

**Comment by katholt** [comment]
That is your own computer system asking for your password, which is required to run 'sudo'
https://en.wikipedia.org/wiki/Sudo
