### ISSUE TITLE
srst2_and_bowtie2

### ISSUE THREAD

**Issue by MariaPerezVazquez** [katholt/srst2#135]
I am using srst2 to look for resistance gene, it use to work properly, I run it with the following syntax 

srst2 --input_pe /processing_Data/antibioticos/mperezv/ANALYSIS/BROTES_RUTINA/reads/K13377_R2.fastq.gz /processing_Data/antibioticos/mperezv/ANALYSIS/BROTES_RUTINA/reads/K13377_R2.fastq.gz --forward _R1 --reverse _R2 --output K13377 --log --gene_db /home/mperezv/Documents/arg-annot-v4-aa-may2018_doc.fasta

and I get the following error
Error: Must specify at least one read input with -U/-1/-2
(ERR): bowtie2-align exited with value 1

Any help will be great

Thank you 
María

**Comment by katholt** [comment]
Hi Maria, it looks like a simple typo in your command - you are supplying the same reverse-reads fastq file (R2) twice, instead of one forward (R1) and one reverse (R2).
