### ISSUE TITLE
Fails on bowtie 2.2.x series, needs 2.1.0 only?

### ISSUE THREAD

**Issue by tseemann** [katholt/srst2#22]
Seems to require bowtie 2.1.0 specifically? (which is nearly 2 years old now). We have the 2.2.2 version as default, but it fails:

11/28/2014 12:02:04 program started
11/28/2014 12:02:04 command line: /bio/sw/srst2/bin/srst2 --input_pe ../dropbox/E.faecium/ALL/Ef_aus2223/aus2223_S141_L002_R1_001.fastq.gz ../dropbox/E.faecium/ALL/Ef_aus2223/aus2223_S141_L002_R2_001.fastq.gz --output Aus2223_mlst --log --mlst_db Enterococcus_faecium.fasta --mlst_definitions efaecium.txt
11/28/2014 12:02:04 Total paired readsets found:1
11/28/2014 12:02:04 Incorrect version of bowtie installed.
11/28/2014 12:02:04 bowtie version 2.1.0 is required by SRST2.

**Comment by katholt** [comment]
SRST2 has been tested with bowtie2 v2.2.3 and v2.2.4.

Support for this is available in the current version in master branch (as of Dec 2014) and will be in the next release.
