### ISSUE TITLE
VFDB_cdhit_to_csv.py throws KeyError for Mycobacterium

### ISSUE THREAD

**Issue by ppcherng** [katholt/srst2#25]
I am following the directions from https://github.com/katholt/srst2#using-the-vfbd-virulence-factor-database-with-srst2 to generate a VFDB gene database for Mycobacterium. I have already run these commands:

python VFDBgenus.py --infile CP_VFs.ffn
cd-hit -i Mycobacterium.fsa -o Mycobacterium_cdhit90 -c 0.9 > Mycobacterium_cdhit90.stdout
(FYI, I am using cd-hit-v4.6.1-2012-08-27)

But when I run this command:
python VFDB_cdhit_to_csv.py --cluster_file Mycobacterium_cdhit90.clstr --infile Mycobacterium.fsa --outfile Mycobacterium_cdhit90.csv

I get this error:
Traceback (most recent call last):
  File "/install/srst2/database_clustering/VFDB_cdhit_to_csv.py", line 66, in <module>
    sys.exit(main())
  File "/install/srst2/database_clustering/VFDB_cdhit_to_csv.py", line 59, in main
    clusterid = seq2cluster[seqID]
KeyError: 'R027152'

**Comment by katholt** [comment]
Fix posted, thanks ppcherng
