### ISSUE TITLE
Analyzing NextSEq data

### ISSUE THREAD

**Issue by tomitaMDU** [katholt/srst2#35]
Hi Kat,

I got NextSeq data which contains 4X forward fastq files and 4X reverse fastq files, in total 8 files for each sample.  I concatenated 4 forward fastq files and 4 reverse fastq files to one forward and reverse fastq files, and run SRST2 but it seems like not processing the run.

Please tell me how to handle such multiple fastq files for SRST2.

Best regards,
Tomi

**Comment by ppcherng** [comment]
Hi Tomi,

I've never run SRST2 with any NextSeq data, but I have run with a bunch of paired end fastq files concatenated to each other seemingly without problems. What are the commands you're running and what error message are you getting?

-Paul

**Comment by tomitaMDU** [comment]
Hi Paul,


I tried last week and used brantfaircloth<https://gist.github.com/brantfaircloth> / merge_next_seq.py<https://gist.github.com/brantfaircloth/d69387a8fe3e8eae9860> https://gist.github.com/brantfaircloth/d69387a8fe3e8eae9860, then SRST2 worked nicely.

Thank you very much.
Best regards,

Takehiro Tomita, PhD

Molecular Scientist

Microbiological Diagnostic Unit - Public Health Laboratory
Department of Microbiology & Immunology
Peter Doherty Institute for Infection and Immunity
The University Of Melbourne

Address: Level 1,792 Elizabeth Street (Corner of Grattan & Elizabeth Streets) Melbourne 3010
Department of Microbiology & Immunology
The University of Melbourne at Peter Doherty Institute for Infection and Immunity – Enter Foyer and take a lift to Level 1.

Phone 1:+61 3 83445713
Phone 2:+61 3 83445701
Fax: +61 3 83447833
