### ISSUE TITLE
Crash during processing of large number of compiledResults.txt files into a single output

### ISSUE THREAD

**Issue by swlong** [katholt/srst2#38]
Running into an error while trying to use --prev_output to aggregate a large number of compiledResults from MLST & Antibiotic resistance gene database into a single report. Sample size is 932 samples. Following error is thrown during the processing phase:

Traceback (most recent call last):
File "/share/apps/srst2/bin/srst2.py", line 1592, in 
main()
File "/share/apps/srst2/bin/srst2.py", line 1583, in main
compile_results(args,mlst_results_hashes,gene_result_hashes,compiled_output_file)
File "/share/apps/srst2/bin/srst2.py", line 1439, in compile_results
this_st = mlst_results_master[sample].split("\t")[1]
IndexError: list index out of range

I'm assuming it's something about the sheer number of samples? or perhaps the compiledResults files.

Best regards,
S. Wesley Long

**Comment by swlong** [comment]
Worth noting, I reran a reduced version of the same dataset (n=739) through srst2 and it worked fine.

**Comment by katholt** [comment]
Hi Scott, I'm just trying to clean up remaining issues for the new release, did you figure out what was going wrong here? We have used the compile function on this number of samples before, and I don't *think* the number of input files would create an issue. 
The error message indicates that we are expecting to see a MLST result and the expected string is not present, so it may just be that one file had an error or failed to call a ST and excluding that file let things work properly...?

**Comment by swlong** [comment]
Sorry, just circling back. I believe it was an error related to a specific input file but I haven't nailed down exactly what that error was. I have been working on some other projects but should be back to working with SRST2 again soon and if it happens again I will update with more info.
