### ISSUE TITLE
grep gene name syntax error

### ISSUE THREAD

**Issue by tcyee91** [katholt/srst2#55]
Hi,

I have this issue at the end of running srst2 using resistance gene database. I don't find any problem with the result but I want to clarify this error with you. Is this error a significant one or it just output error with the gene naming but doesn't affect the result?

sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `grep 194__mph(A)_1_D16251__mph(A)_1_D16251__00057 /database/resfinder2016_2.fasta'

Thanks,
Cheng

**Comment by katholt** [comment]
Looks like a problem with the '()' characters in fasta headers.
This won't affect your results as it's just occurring when we try to extract additional annotation information for the gene, it's not affecting the output. 
You could either remove any brackets from the headers in your fasta file, or use the updated resistance gene DB we provide, ie https://github.com/katholt/srst2/blob/master/data/ARGannot.r1.fasta
