### ISSUE TITLE
single end and paired end reads for a sample

### ISSUE THREAD

**Issue by tcyee91** [katholt/srst2#56]
Hi Kat,

I have single end read (merged from paired end reads) and paired end reads (remaining result of not merged) for a sample and I am using all for one srst2 run. I am not sure if the --merge_paired option is used for this condition? Because when I tried I got this error:

File "/srst2/srst2.py", line 1514, in main
    mate2.append(reads[1])
IndexError: list index out of range

Please advise. Many thanks.

Regards,
Cheng

**Comment by katholt** [comment]
Hi Cheng,
--merge_paired is set up to merge 2 sets of read pairs, e.g. if you sequence the same strain twice and end up with two read pairs. I don't think we've explicitly coded a solution for merging single end + paired end reads. I can have a look but too busy at the moment.
However in your case, have you tried just using your raw (unmerged) paired end reads as input, and not worrying about merging overlapping reads first? The bowtie2 aligner should be able to handle this just fine, see http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#mates-can-overlap-contain-or-dovetail-each-other.
Kat

**Comment by tcyee91** [comment]
I see. Yeap, I have tried the raw paired end reads and they worked fine. I was just thinking maybe to standardize my input for analysis since I used the pre-processed reads for other downstream analysis. Thank you for your verification.

Cheers,
Cheng
