### ISSUE TITLE
Nb. User error using getmlst.py script

### ISSUE THREAD

**Issue by swlong** [katholt/srst2#58]
I just wanted to note this user error which I managed to run afoul of in the past week. If one updates the MLST database files with the getmlst.py script in the same directory where an older version of the files is stored, it will overwrite the alleles files (tfa and fasta) and the ST definition text file, however it leaves the bowtie2 and samtools generated index files intact. 

If you neglect to remember this and fail to remove these files manually, SRST2 will subsequently run quite happily and generate a slew of rather erroneous results using the bad index files and the new data files. As far as I can tell, no errors are generated, per se, but the resulting MLST calls are mostly NF*? due to terrible mismatches as the indices don't match the new data files. 

It might be nice if the getmlst script removed the old indexes and perhaps even generated the new ones after downloading the MLST database files, but I leave that decision up to you. 

Best,
S. Wesley Long

**Comment by rrwick** [comment]
Thanks for pointing this out! It's been fixed in: https://github.com/katholt/srst2/commit/e70952326a893ae22838cbd3535c980d98bfe53e
