### ISSUE TITLE
Why are my isolate names appended with a '?' in some cases but not all?

### ISSUE THREAD

**Issue by schultzm** [katholt/srst2#65]
When running the command 
`srst2 --prev_output *_genes__*__results.txt --output xyz`
Why are some isolate names appended with a '?' in the output table?

**Comment by katholt** [comment]
Don't know, we have not seen this behaviour. Are you using the latest version, and can you give an example of input files that produce this behaviour please?

**Comment by rrwick** [comment]
Fixed in this commit: https://github.com/katholt/srst2/commit/dfb470665de6f91683702bdb05a27cea66bc281c
