### ISSUE TITLE
Could not determine forward/reverse read status for input file

### ISSUE THREAD

**Issue by FelipeMelis** [katholt/srst2#71]
Hello

The reads subjected to trimming are not detected as forward or reverse by srst2 and i obtain the following error:

`09/08/2016 13:18:04 Could not determine forward/reverse read status for input file SaB1_1_trimmed.fastq
09/08/2016 13:18:04 Could not determine forward/reverse read status for input file SaB1_2_trimmed.fastq`

**Comment by katholt** [comment]
This is because your read files are not named in a format that SRST2 understands. Please see the readme https://github.com/katholt/srst2#input-read-formats-and-options

Basically if you name the files as SaB1_trimmed_1.fastq and SaB1_trimmed_2.fastq it should work fine.
