### ISSUE TITLE
Provide FASTA via --gene_db but SRST2 seems to expect bowtie index?

### ISSUE THREAD

**Issue by mw55309** [katholt/srst2#79]
Hey

So the documentation definitely states that --gene_db should be a fasta file, and I used ARGannot.r1.fasta in my tests.

However, all my jobs failed as Bowtie2 failed; and bowtie2 failed because ARGannot.r1.fasta is not an index...

This could be because I submitted 48 jobs simultaneously.  

Is it possible that all 48 jobs tried to create the same index??

Cheers
Mick

**Comment by mw55309** [comment]
OK, answered my own question!

My guess is 1st time run creates faidx and bowtie2 indices, so submitting multiple jobs simulatenously creates clashes as multiple jobs attempt the first time index build.

**Comment by katholt** [comment]
See https://github.com/katholt/srst2#known-issues
