### ISSUE TITLE
failed to plot figure using R

### ISSUE THREAD

**Issue by xthua** [katholt/srst2#81]
hi, i tried to plot the figure using R, but failed. the error information was listed below:
> geneContentPlot(m=Ef_JAMA, mlst_columns = 2:9, gene_columns = 13:31, strain_names=1, cluster=T, labelHeight=40, infoWidLoading required package: ape
The "ward" method has been renamed to "ward.D"; note new "ward.D2"
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by katholt** [comment]
Hi xthua,
It's hard to comment on this without knowing what you are trying to do. Are you just trying to follow the example in the readme? Did you paste in the full command? (I can't tell from what's pasted above).
If you provide a bit more info I can try to help you, although the R plotting scripts are really just provided to show how we made the figures in the paper and to help users get started on making figures from their own output in R.

**Comment by mushalallam** [comment]
Hi @katholt,
I got the same error above, I'm trying to follow the example in the readme

> geneContentPlot(m=Ef_JAMA, mlst_columns = 2:9, gene_columns = 13:31, strain_names=1, cluster=T, labelHeight=40, infoWidth=15, treeWidth=5)
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

Please advise.

Thanks

**Comment by singuyenmai** [comment]
Hello there,

I see that this issue has been closed. However, I am also facing the same problem while using the script cloning from the GitHub repos. Seems like this hasn't been fixed for me. Could please help me overcome this error?

Thank you very much in advance.
