### ISSUE TITLE
Delimiter warning for Acinetobacter MLST

### ISSUE THREAD

**Issue by davidwcleary** [katholt/srst2#84]
Hello, 

Have been using SRST2 for a couple of years now and never had an issue (which has been amazing!).  However this is the first time I've tried to use it with Acinetobacter baumannii and I'm wondering if I'm missing a step.  There are two schemes from Oxford and Pasteur so when you download either one of them the alleles are labelled as Pas_cpn60_1 or Oxf_cpn60_1 for example.  When I run either of them, with the delimiter set to '-'  I get the following:

Warning! MLST delimiter is _ but these genes may violate the pattern and cause problems:
(and then all the genes are listed).  

Is the identical first delimiter causing issues? The final output is... 

This combination of alleles was not found in the sequence type database: DMS07800_L7 Pas_rplB_2
04/02/2017 18:41:48  DMS07800_L7	NF	-	0	-	0	0

Apologies if this is a dumb question and thanks for your help,
David

**Comment by katholt** [comment]
Ugh this is something we should fix, if people are going to start annotating their MLST allele names rather than sticking to tradition :)
In the meantime just remove the "Oxf_" and "Pas_" from the fasta and ST files for these schemes and all should work fine.

**Comment by katholt** [comment]
Ryan can you please look at fixing this, it should work if we assume the last delimiter precedes the allele number and everything before the last delimiter is the allele name.

**Comment by davidwcleary** [comment]
Thank you so much for such a quick response!  I had assumed this might be the issue but couldn't understand the logic of why you introduce a random naming convention.  Thanks again :)
