### ISSUE TITLE
cdhit_to_csv.py and IndexError: list index out of range

### ISSUE THREAD

**Issue by TreeT2** [katholt/srst2#89]
Hi All,

Im trying to setup a database for analysis using instructions on https://github.com/katholt/srst2#clusteringsequences
I get as far as step 2 before I get the following error

![image](https://user-images.githubusercontent.com/20044679/27376242-7790223c-5669-11e7-9881-ba0b1b97de7d.png)

my fasta header look like:

![image](https://user-images.githubusercontent.com/20044679/27376295-9400a66c-5669-11e7-8d95-e5897f6e7d79.png)

Thanks

**Comment by katholt** [comment]
This error is in reading the cluster file (.clstr) output by cd-hit-est, not the fasta file.
Are you passing the right output from cd-hit-est to the script via --cluster_file ?
