### ISSUE TITLE
ARGannot.r1 E. coli chromosomal genes

### ISSUE THREAD

**Issue by cahlstrom** [katholt/srst2#97]
Apologies if I have missed this answer somewhere, but I don't quite understand why four E. coli chromosomally encoded genes are included in the ARGannot.r1 database. I am using ESBL-producing E. coli raw reads as input, however SRST2 is not identifying AmpC1_Ecoli_Bla in all of my isolates, despite high coverage (whereas AMPH, AmpC2, and Penicillin_Binding_Protein are found in all isolates). I'm trying to interpret these results, but am unsure why these four genes were included in the database to begin with. Can someone please clarify this?
Many thanks!
Christina

**Comment by katholt** [comment]
We simply provide a SRST2-formatted version of the ARG-Annot database, which is put together by others. Please see the ARG-Annot paper for more info about what they include/exclude.
https://www.ncbi.nlm.nih.gov/pubmed/24145532

As a general principle, the DB includes many genes that are intrinsic to some bacteria but have been mobilised and are thus acquired in other bacteria; e.g. aac6 in Salmonella or blaSHV in Klebsiella. 

As to why ampC1 is not identified in all isolates, I would try looking at the scores file or fullgenes report to see whether the genes is actually there at low depth or truncated, or not detected at all.
